name: destroy cockroach terraform infra
description: destroy terraform infra. you should execute infra/setup action before.

inputs:
  project_env:
    description: "project env."
    required: true
  gcp_cloud_storage_terraform_bucket:
    description: "name of google cloud storage bucket for tfstate"
    required: true
  secret_cockroach_api_key:
    description: "secret of cockroach api key"
    required: true
  secret_cockroach_sql_user_password:
    description: "secret of cockroach sql user password"
    required: true  
  working-directory:
    description: "working directory"
    default: ""

runs:
  using: composite
  steps:
    - name: Download .tfstate file from GCS
      working-directory: ${{ inputs.working-directory }}
      run: gcloud storage cp gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/cockroach/terraform.tfstate terraform.tfstate
      shell: sh

    - name: Terraform init
      working-directory: ${{ inputs.working-directory }}
      run: terraform init
      shell: sh

    - name: Terraform plan
      working-directory: ${{ inputs.working-directory }}
      env: 
        COCKROACH_API_KEY: ${{ inputs.secret_cockroach_api_key }} 
      run: |
        terraform plan -destroy \
          -var='project_prefix=mndp' \
          -var='project_env=${{ inputs.project_env }}' \
          -var='sql_user_password=${{ inputs.secret_cockroach_sql_user_password }}'
      shell: sh

    - name: Terraform destroy
      working-directory: ${{ inputs.working-directory }}         
      env: 
        COCKROACH_API_KEY: ${{ inputs.secret_cockroach_api_key }} 
      run: |
        terraform destroy \
          -auto-approve \
          -var='project_prefix=mndp' \
          -var='project_env=${{ inputs.project_env }}' \
          -var='sql_user_password=${{ inputs.secret_cockroach_sql_user_password }}'
      shell: sh

    - name: Upload .tfstate file to GCS
      working-directory: ${{ inputs.working-directory }}
      run: gcloud storage cp terraform.tfstate gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/cockroach/terraform.tfstate
      shell: sh
