options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "gcr.io/$PROJECT_ID/ko-builder"
    env:
      - "KO_DOCKER_REPO=gcr.io/$PROJECT_ID"
      - "SOURCE_DATE_EPOCH=$(date +%s)"
    args:
      - "run"
      - "deploy"
      - "platform"
      - "--image"
      - $(KO_DOCKER_REPO=$KO_DOCKER_REPO SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH ko build ./)
      - "--region"
      - "asia-northeast1"
