options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "gcr.io/$PROJECT_ID/ko-builder"
    script: |
      gcloud run \
      deploy platform \
      --image $(KO_DOCKER_REPO=$KO_DOCKER_REPO ko build ./) \
      --region asia-northeast1
