options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "gcr.io/spartan-matter-356507/aqua-builder:latest"
    script: |
      aqua i
      buf generate
    dir: "api"
  - name: "gcr.io/spartan-matter-356507/aqua-builder:latest"
    script: |
      aqua i
      go generate ./...
      wire
    dir: "backend"
  - name: "gcr.io/$PROJECT_ID/ko-builder"
    env:
      - "KO_DOCKER_REPO=gcr.io/$PROJECT_ID"
    script: |
      gcloud run \
      deploy platform \
      --image $(SOURCE_DATE_EPOCH=$(date +%s) ko build ./) \
      --region asia-northeast1
    dir: "backend"
