options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "gcr.io/$PROJECT_ID/ko-builder"
    env:
      - "DEPLOY_IMAGE=$(KO_DOCKER_REPO=gcr.io/$PROJECT_ID SOURCE_DATE_EPOCH=$(date +%s) ko build ./)"
    args:
      - "run"
      - "deploy"
      - "platform"
      - "--image"
      - "$DEPLOY_IMAGE"
      - "--region"
      - "asia-northeast1"
