options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # 前回成功した際のcommit hashを取得するために必要
  # gcloudジョブ内でgit fetch --unshallowしてもなぜか取得できなかったのでジョブを分けた
  # @see https://github.com/GoogleCloudPlatform/professional-services/blob/main/examples/cloudbuild-selective-deployment/cloudbuild.yaml
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']
  # Github Actionsにてyqコマンドでこのステップの順番を決め打ちで書き換えている。
  # このステップの順番が変わった場合はbackend.container.core.ymlで実行しているyqコマンドの引数も同時に修正すること
  - name: gcr.io/cloud-builders/gcloud
    env:
      - SERVICE_NAME=$_SERVICE_NAME
      - GCP_REPO=gcr.io/$PROJECT_ID
      # IMAGE_NAME、IMAGE_TAGはGithub Actionsにてyqコマンドで順番を決め打ちで書き換えている。
      # 順番が変わった場合はbackend.container.core.ymlで実行しているyqコマンドの引数も同時に修正すること
      - IMAGE_NAME=mndp-core
      - IMAGE_TAG=v20221113090143
      - REVISION_SERVICE_ACCOUNT=$_REVISION_SERVICE_ACCOUNT
      - API_KEY=${_API_KEY}
      - DATABASE_URL=${_DATABASE_URL}
      - PROJECT_ID=$PROJECT_ID
      - TRIGGER_NAME=$TRIGGER_NAME
      - TRIGGER_BUILD_CONFIG_PATH=$TRIGGER_BUILD_CONFIG_PATH
    script: |
      bash infra/gcp/cloudbuild/script/deploy.sh \
        $SERVICE_NAME \
        $GCP_REPO \
        $IMAGE_NAME \
        $IMAGE_TAG \
        $REVISION_SERVICE_ACCOUNT \
        $API_KEY \
        $DATABASE_URL \
        $PROJECT_ID \
        $TRIGGER_NAME \
        $TRIGGER_BUILD_CONFIG_PATH
