name: set up google cloud authenticate
description: use google cloud storage

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      uses: "google-github-actions/auth@v0"
      with:
        workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up gcloud
      uses: "google-github-actions/setup-gcloud@v0"

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v2
