name: deproy terraform infra
description: deploy terraform infra. you should execute infra/setup action before.

inputs:
  project_env:
    description: "project env. ex. prod"
    required: true
  deploy:
    description: "whether to deploy. true/false. default true."
    default: 'true'
  lint:
    description: "whether to lint. true/false. default true."
    default: 'true'
  first_deploy:
    description: "whether deploy to this env is first time. true/false. default false."
    default: 'false'
  gcp_cloud_storage_terraform_bucket:
    description: "name of google cloud storage bucket for tfstate"
    required: true
  secret_cockroach_api_key:
    description: "secret of cockroach api key"
    required: true
  secret_cockroach_sql_user_password:
    description: "secret of cockroach sql user password"
    required: true  
  working-directory:
    description: "working directory"
    default: ""

runs:
  using: composite
  steps:
    - name: Download .tfstate file from GCS
      # 初回の場合は.tfstateファイルが存在せずエラーとなるので、初回でない時のみ実行する
      if: ${{ inputs.first_deploy == 'false' }}
      shell: sh
      run: gcloud storage cp gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/cockroach/terraform.tfstate terraform.tfstate
      working-directory: ${{ inputs.working-directory }}

    - name: Terraform init
      shell: sh
      run: terraform init
      working-directory: ${{ inputs.working-directory }}
    
    - name: Terraform format
      if: ${{ inputs.lint == 'true' }}
      shell: sh
      run: terraform fmt -recursive -check
      working-directory: ${{ inputs.working-directory }}

    - name: Terraform validate
      if: ${{ inputs.lint == 'true' }}
      shell: sh
      run: terraform validate
      working-directory: ${{ inputs.working-directory }}


    - name: Terraform plan
      if: ${{ inputs.lint == 'true' }}
      shell: sh
      env: 
        COCKROACH_API_KEY: ${{ inputs.secret_cockroach_api_key }} 
      run: |
        terraform plan \
          -var='project_prefix=mndp' \
          -var='project_env=${{ inputs.project_env }}' \
          -var='sql_user_password=${{ inputs.secret_cockroach_sql_user_password }}'
      working-directory: ${{ inputs.working-directory }}

    - name: Terraform apply
      if: ${{ inputs.deploy == 'true' }}
      shell: sh
      env: 
        COCKROACH_API_KEY: ${{ inputs.secret_cockroach_api_key }} 
      run: |
        terraform plan \
          -var='project_prefix=mndp' \
          -var='project_env=${{ inputs.project_env }}' \
          -var='sql_user_password=${{ inputs.secret_cockroach_sql_user_password }}'
      working-directory: ${{ inputs.working-directory }}         

    - name: Upload .tfstate file to GCS
      if: ${{ inputs.deploy == 'true' }}
      shell: sh
      run: gcloud storage cp terraform.tfstate gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/cockroach/terraform.tfstate
      working-directory: ${{ inputs.working-directory }}
