name: "Backend Common Action"
description: "Backend Common Action"

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Set up connect
      shell: bash
      run: |
        go install github.com/bufbuild/buf/cmd/buf@latest
        go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
    - name: Generate connect code
      shell: bash
      run: |
        npm install
        buf generate
      working-directory: ./api
    - name: Go generate
      shell: bash
      run: go generate ./...
      working-directory: ./backend
