version: "3.8"
services:
  db:
    container_name: ${APP_NAME}-db
    image: postgres:${POSTGRES_VERSION}-alpine
    ports:
      - 54321:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
  app-core:
    container_name: ${APP_NAME}-app-core
    build:
      context: .
      dockerfile: core/Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    ports:
      - 8081:8080
    environment:
      DOMAIN: http://localhost:8081
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      API_KEY: local
      ENV: ${ENV}
      FIREBASE_SECRET: ${FIREBASE_SECRET}
      FIREBASE_API_ENDPOINT: ${FIREBASE_API_ENDPOINT}
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
    volumes:
      - ../backend:/app
    restart: always
    depends_on:
      - db
  db-migration:
    container_name: ${APP_NAME}-db-migration
    build:
      context: .
      dockerfile: migration/Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    volumes:
      - ../backend:/app
    depends_on:
      - db
