name: destroy gcp terraform infra
description: deploy terraform infra. you should execute infra/setup action before.

inputs:
  project_env:
    description: "project env."
    required: true
  gcp_project_id:
    description: "gcp project id"
    required: true
  gcp_cloud_storage_terraform_bucket:
    description: "name of google cloud storage bucket for tfstate"
    required: true
  secret_core_api_key:
    description: "secret of core api key"
    required: true
  secret_core_database_url:
    description: "secret of database url"
    required: true
  working-directory:
    description: "working directory"
    default: ""

runs:
  using: composite
  steps:
    - name: Download .tfstate file from GCS
      working-directory: ${{ inputs.working-directory }}
      run: gcloud storage cp gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/gcp/terraform.tfstate terraform.tfstate
      shell: sh

    - name: Terraform init
      working-directory: ${{ inputs.working-directory }}
      run: terraform init
      shell: sh

    - name: Terraform plan
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform plan -destroy \
          -var='project_prefix=mndp' \
          -var='project_env=${{ inputs.project_env }}' \
          -var='gcp_credentials_file_path=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}' \
          -var='project_id=${{ inputs.gcp_project_id }}' \
          -var='secret_core_api_key=${{ inputs.secret_core_api_key }}' \
          -var='secret_core_database_url=${{ inputs.secret_core_database_url }}' \
          -var='git_repository_owner=${{ github.repository_owner }}' \
          -var="git_repository_name=$(echo ${{ github.repository }} | awk -F'[/]' '{print $2}')" \
      shell: sh

    - name: Terraform destroy
      working-directory: ${{ inputs.working-directory }}          
      run: |
        terraform destroy \
          -auto-approve \
          -var='project_prefix=mndp' \
          -var='project_env=${{ inputs.project_env }}' \
          -var='gcp_credentials_file_path=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}' \
          -var='project_id=${{ inputs.gcp_project_id }}' \
          -var='secret_core_api_key=${{ inputs.secret_core_api_key }}' \
          -var='secret_core_database_url=${{ inputs.secret_core_database_url }}' \
          -var='git_repository_owner=${{ github.repository_owner }}' \
          -var="git_repository_name=$(echo ${{ github.repository }} | awk -F'[/]' '{print $2}')" \
      shell: sh

    - name: Upload .tfstate file to GCS
      working-directory: ${{ inputs.working-directory }}
      run: gcloud storage cp terraform.tfstate gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/gcp/terraform.tfstate
      shell: sh
