name: api document

on:
  pull_request:

jobs:
  document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Confirm
        run: ls -la

      - name: Set up protoc
        uses: arduino/setup-protoc@v1

      - name: Generate grpc document
        working-directory: main
        run: |
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
          mkdir -p public/api
          protoc --doc_out=./public/api --doc_opt=markdown,README.md $(find api -name '*.proto')

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
