name: api check
on:
  pull_request:
    paths:
      - api/**/*.proto
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: 'latest'
      - name: Buf lint
        working-directory: ./api/proto
        run: buf lint
      - name: Buf format
        working-directory: ./api
        run: buf format -d --exit-code
