name: backend e2e test
on:
  pull_request:
    paths:
      - .github/workflows/backend.test.e2e.yaml
      - api/**/*.proto
      - backend/**/*.go
      - backend/go.mod
      - backend/go.sum
jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.6-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Migrate
        working-directory: ./backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
        run: go run cmd/migrate/main.go
      - name: Go run core
        working-directory: ./backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
          API_KEY: e2e
        run: |
          go run cmd/core/main.go &
          echo PID=$! >> $GITHUB_ENV
          sleep 10
      - name: Go test e2e
        working-directory: ./backend
        env:
          ENDPOINT: http://localhost:8080
          API_KEY: e2e
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
        run: go test ./e2e/... -tags e2e
      - name: Shutdown
        if: always()
        run: kill ${{ env.PID }}
