name: backend test

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - .github/workflows/backend.test.yml
      - api/**/*.proto
      - backend/**/*.go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod

      - name: Go Test
        working-directory: ./backend
        run: go test ./...

      - name: coverage
        working-directory: ./backend
        run: |
          go test ./...  -coverpkg=./... -coverprofile ./coverage.txt

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
