name: backend container core

env:
  PROJECT_PREFIX: mngp
  PROJECT_ENV: prod
  SERVICE_NAME: core

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  container:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.build-and-push.outputs.image_name }}
      image_tag: ${{ steps.build-and-push.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
   
      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: "google-github-actions/setup-gcloud@v0"
        
      - name: Build and Push
        uses: ./.github/actions/backend/container
        with:
          gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          project_prefix: ${{ env.PROJECT_PREFIX }}
          project_env: ${{ env.PROJECT_ENV }}
          service_name: ${{ env.SERVICE_NAME }}

  deploy:
    needs: container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy
        run: |
          export IMAGE_NAME=${{needs.container.outputs.image_name}}
          export IMAGE_TAG=${{needs.container.outputs.image_tag}}
          gcloud run deploy mndp-core \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$IMAGE_TAG \
            --region asia-northeast1 \
            --cpu 1 \
            --memory 128Mi \
            --max-instances 1 \
            --service-account ${{ secrets.GCP_CLOUDRUN_SERVICE_ACCOUNT }} \
            --set-secrets API_KEY=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/mndp-prod-core-api-key:latest \
            --set-secrets DATABASE_URL=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/mndp-prod-core-database-url:latest \
            --allow-unauthenticated
