name: integration test
on:
  pull_request:
    paths:
      - .github/workflows/backend.integration.test.yaml
      - api/**/*.proto
      - backend/**/*.go
      - backend/go.mod
      - backend/go.sum
jobs:
  integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.6-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Integration test
        working-directory: ./backend
        env:
          POSTGRES_IMAGE: postgres:14.6-alpine
        run: go test ./internal/database/store/... -tags integration
