name: check

on:
  pull_request:
    paths:
      - api/**/*.proto
      - backend/**/*.go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up
        uses: ./.github/actions/backend/setup

      - name: Generate connect code
        working-directory: ./api
        run: buf generate --template buf.backend.gen.yaml

      - name: Generate go code
        working-directory: ./backend
        run: go generate ./...

      - name: Go mod tidy
        working-directory: ./backend
        run: go mod tidy

      - name: Check diff
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git status --porcelain;
            exit 1;
          else
            echo "no changes";
          fi
