name: backend test
on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - .github/workflows/backend.test.yaml
      - api/**/*.proto
      - backend/**/*.go
      - backend/go.mod
      - backend/go.sum
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Go Test
        working-directory: ./backend
        run: go test ./...
      - name: coverage
        working-directory: ./backend
        run: |
          go test ./...  -coverpkg=./... -coverprofile ./coverage.txt
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
