name: deploy

on:
  workflow_run:
    workflows: ["build"]
    branches: [main]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      REPO_NAME: asia.gcr.io/spartan-matter-356507
      IMAGE_NAME: article-share
      IMAGE_TAG: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_POOL }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_FOR_GCR }}
          audience: https://github.com/morning-night-dream
      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v0"
      - name: Set up docker auth
        run: gcloud auth configure-docker
      - uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: article-share/build-artifact
      - name: Setup Artifact
        run: cp article-share/build-artifact/main backend/main
      - name: Build & Push
        env:
          IMAGE: ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          docker build -t ${{ env.IMAGE }} .
          docker push ${{ env.IMAGE }}
        working-directory: ./backend
