name: document

on:
  pull_request:

permissions:
  contents: write

jobs:
  document:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
      - name: Set up tbls
        run: go install github.com/k1LoW/tbls@main
      - name: Set up protoc
        uses: arduino/setup-protoc@v1
      - name: Set up connect
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
      - name: Generate connect code
        working-directory: ./api
        run: buf generate
      - name: Go Generate
        working-directory: ./backend
        run: go generate ./...
      - name: Set up wire
        working-directory: ./backend
        run: |
          go install github.com/google/wire/cmd/wire@latest
          wire
      - name: Migrate
        working-directory: ./backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
        run: go run cmd/migrate/main.go
      - name: Generate database document
        run: tbls doc "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable" document/database
      - name: Generate grpc document
        run: |
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
          mkdir -p document/grpc
          protoc --doc_out=./document/grpc --doc_opt=markdown,document.md ./api/**/*.proto
      - name: Git push
        working-directory: ./document
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git checkout --orphan document
          git rm -rf
          git config --global user.email "morning.night.dream@gmail.com"
          git config --global user.name "morning-night-dream"
          git add -A
          git commit -m "docs create from github actions"
          git push --force --quiet "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" document
