name: frontend lint
on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - frontend/*
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up
        uses: ./.github/actions/frontend/setup
      - name: Install
        working-directory: ./frontend
        run: yarn install
      - name: Build
        working-directory: ./frontend
        run: yarn build
      - name: Lint
        working-directory: ./frontend
        run: yarn xo
