name: infra cockroach lint

on:
  pull_request:
    paths:
      - .github/workflows/infra.cockroach.lint.yml
      - infra/cockroach/*

defaults:
  run:
    working-directory: ./infra/cockroach

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up
        uses: ./.github/actions/infra/setup
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Terraform format
        run: terraform fmt -recursive -check

      - name: Download .tfstate file from GCS
        run: gcloud storage cp gs://${{ secrets.GCP_CLOUD_STORAGE_TERRAFORM_BUCKET }}/cockroach/terraform.tfstate terraform.tfstate

      - name: Terraform check
        env: 
          COCKROACH_API_KEY: ${{ secrets.COCKROACH_API_KEY }} 
        run: |
          terraform init
          terraform validate
          terraform plan \
            -var='cluster_name=${{ secrets.COCKROACH_CLUSTER_NAME }}' \
            -var='sql_user_name=${{ secrets.COCKROACH_SQL_USER_NAME }}' \
            -var='sql_user_password=${{ secrets.COCKROACH_SQL_USER_PASSWORD }}'
