name: infra cockroach deploy

on:
  workflow_dispatch:
  push:

defaults:
  run:
    working-directory: ./infra/cockroach

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up
        uses: ./.github/actions/infra/setup
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Terraform apply
        env: 
          COCKROACH_API_KEY: ${{ secrets.COCKROACH_API_KEY }} 
        run: |
          terraform init
          terraform apply \
            -auto-approve \
            -var='cluster_name=${{ secrets.COCKROACH_CLUSTER_NAME }}' \
            -var='sql_user_name=${{ secrets.COCKROACH_SQL_USER_NAME }}' \
            -var='sql_user_password=${{ secrets.COCKROACH_SQL_USER_PASSWORD }}'

      - name: Upload .tfstate file to GCS
        run: |
          gcloud storage cp terraform.tfstate gs://${{ secrets.GCP_CLOUD_STORAGE_TERRAFORM_BUCKET }}/cockroach/terraform.tfstate
          gcloud storage cp terraform.tfstate.backup gs://${{ secrets.GCP_CLOUD_STORAGE_TERRAFORM_BUCKET }}/cockroach/terraform.tfstate.backup
