name: infra gcp lint

on:
  pull_request:
    paths:
      - .github/workflows/infra.gcp.lint.yml
      - infra/gcp/*

defaults:
  run:
    working-directory: ./infra/gcp

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform format
        run: terraform fmt -recursive -check

      - name: Terraform check
        run: |
          terraform init
          terraform validate
          terraform plan \
            -var='gcp_credentials=${{ secrets.GCP_CREDENTIALS }}' \
            -var='project_id=${{ secrets.GCP_PROJECT_ID }}' \
            -var='secret_core_api_key=${{ secrets.GCP_CORE_API_KEY }}' \
            -var='secret_core_database_url=${{ secrets.GCP_CORE_DATABASE_URL }}'
