name: release

on:
  push:
    branches:
      - "main"
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Set up connect
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
      - name: Generate connect code
        run: buf generate
        working-directory: ./api
      - name: Go generate
        run: go generate ./...
        working-directory: ./backend
      - name: Set version
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Docker Login
        run: echo "${{ secrets.GIT_DOCKER_PAT }}" | docker login ghcr.io -u ${OWNER,,} --password-stdin
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
