name: release

on:
  push:
    branches:
      - "main"
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up
        uses: ./.github/actions/setup
      - name: Generate connect code
        run: |
          npm install
          buf generate
        working-directory: ./api
      - name: Go generate
        run: go generate ./...
        working-directory: ./backend
      - name: Set version
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Docker Login
        run: echo "${{ secrets.GIT_DOCKER_PAT }}" | docker login ghcr.io -u ${OWNER,,} --password-stdin
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./backend/app/core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
