name: renovate

on:
  push:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.RENOVATOR_APP_PEM }}
          APP_ID: ${{ secrets.RENOVATOR_APP_ID }}

      - name: Self hosted Renovate
        uses: renovatebot/github-action@v32.238.4
        with:
          configurationFile: .github/renovate.json5
          token: ${{ steps.get_token.outputs.app_token }}
        env:
          LOG_LEVEL: 'debug'
