name: test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up
        uses: ./.github/actions/goaqua
      - name: Generate connect code
        working-directory: ./api
        run: buf generate
      - name: Go Test
        working-directory: ./backend
        run: |
          go generate ./...
          go test ./...
      - name: coverage
        working-directory: ./backend
        run: |
          go test ./...  -coverpkg=./... -coverprofile ./coverage.txt
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
