options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "gcr.io/$PROJECT_ID/builder"
    script: |
      aqua i
      buf generate --template buf.backend.gen.yaml
    dir: "api"
  - name: "gcr.io/$PROJECT_ID/builder"
    script: |
      aqua i
      go generate ./...
      wire gen ./app/core
    dir: "backend"
  - name: "gcr.io/$PROJECT_ID/deployer"
    env:
      # 1番目の環境変数はイメージ名+タグとする。Github Actionsにてyqコマンドで決め打ちで書き換えるため
      - "IMAGE_NAME_WITH_TAG=mndp-core:latest"
      - "DOCKER_REPO=gcr.io/$PROJECT_ID"
      - "REVISION_SERVICE_ACCOUNT=$_REVISION_SERVICE_ACCOUNT"
      - "API_KEY=${_API_KEY}:latest"
      - "DATABASE_URL=${_DATABASE_URL_SECRET}:latest"
    script: |
      gcloud run \
      deploy dream-platform \
        --image $DOCKER_REPO/$IMAGE_NAME_WITH_TAG \
        --region asia-northeast1 \
        --cpu 1 \
        --memory 128Mi \
        --max-instances 1 \
        --service-account $REVISION_SERVICE_ACCOUNT \
        --set-secrets API_KEY=$API_KEY,DATABASE_URL=$DATABASE_URL \
        --allow-unauthenticated
    dir: "backend/app/core"
